name: build
# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.
on:
  push:
  pull_request:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        include:
          - java: 21
            minecraft_version: "1.8.9"
            forge_version: "11.15.1.2318-1.8.9"
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: build
        run: ./gradlew build

      - name: Rename artifact
        run: |
          cd build/libs/
          for file in skycofl-*-all.jar; do
            if [ -f "$file" ]; then
              mv "$file" "SkyCofl-1.8.0-Forge-1.8.9.jar"
            fi
          done

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SkyCofl-1.8.0-Forge-1.8.9
          path: build/libs/SkyCofl-1.8.0-Forge-1.8.9.jar

      - name: Publish (CurseForge/Modrinth)
        uses: Kir-Antipov/mc-publish@v3.3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          modrinth-id: yso5yMlC
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 1286702
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          # general settings
          name: "${{ github.ref_name }} ${{ matrix.minecraft_version }}"
          version: "${{ github.ref_name }}_Forge_${{ matrix.minecraft_version }}"
          changelog: |
            ➡️ Bug Fixes and Improvements
            ${{ github.event.release.body }}
            For 1.21+ versions please check out the [Fabric version](https://github.com/Coflnet/SkyblockmodFabric/releases).
            [View on GitHub Releases](https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }})
          loaders: forge
          game-versions: "${{ matrix.minecraft_version }}"
          java: "21"
          version-type: release

          files: |
            build/libs/!(*-@(dev|sources|javadoc)).jar
          dependencies: |
            forge@${{ matrix.forge_version }}(required)

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/libs/!(*-@(dev|sources|javadoc)).jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
